### ISSUE TITLE
IndexError with salt processing in client.py

### ISSUE THREAD

**Issue by AndreQuintas** [SICKAG/sick_scan_rest_client#1]
Hello ,

Firstly, I want to express my gratitude for providing the library. Altough i am having troubles ('IndexError: list index out of range') with the following lines :

for i in salt:
     saltBinary = saltBinary + chr(salt[i])

Shouldn't it be : 'saltBinary = saltBinary + chr(i)' ?
Despite having changed it, I still receive 'Access Denied'.

Could you please provide any insights or suggestions on how to resolve this issue?

Thank you for your assistance.

Best regards,
André.

**Comment by gschwsiSICKAG** [comment]
Hi André, 

Thanks for reporting. We have identified the issue and working on a solution. 

Please make sure you watch the repo so you don’t miss the release, which we publish as soon as possible.

**Comment by gschwsiSICKAG** [comment]
Hi André,

have you tested the latest changes?

**Comment by AndreQuintas** [comment]
Hello,

The new version is working perfectly. Much appreciated for the assistance !
